Rack lesson
CepCap/rack_example pull request #1
Opened 2019-03-06 03:08 UTC by CepCap

2019-03-06 15:51 UTC, BubuntuClu commented on rack/app.rb
> +  def query_check(query_string)
эту всю проверку хорошо вынести в отдельный класс/сервис, который будет за нее отвественный. приложению не надо об этом знать ничего

2019-03-06 15:51 UTC, BubuntuClu commented on rack/app.rb
> +  def time_check(format)
это можно реализовать более красиво, на мой взгляд
```
AVAILABLE_FORMATS = {
  'year'    => '%Y',
  'month'   => '%m',
  'day'     => '%d',
  'hour'    => '%H',
  'minute'  => '%M',
  'second'  => '%S'
}
...

def convert_format
  @formats.map do |format,| 
     Time.now.strftime(AVAILABLE_FORMATS[format])
  end.join("-")
end
```

2019-03-06 15:51 UTC, BubuntuClu commented on rack/app.rb
> +  def ok_status
это можно в константу, вместо метода

2019-03-06 16:35 UTC, psylone requested changes

2019-03-06 16:35 UTC, psylone commented on rack/app.rb
> +    format = query_string.gsub(/(=|%2C)/, "|").split("|")
Используй объект класса `Rack::Request` и метод `params`.

2019-03-06 16:35 UTC, psylone commented on rack/app.rb
> +    format.each do |time|
Как и написал Андрей, форматирование фремени необходимо вынести в отдельный класс. Этот класс не должен ничего знать о классе rack приложения. Таким образом мы обеспечим слабую связь между этими классами что позволит, например, использовать класс форматирования времени в другом Ruby приложении (не обязательно rack).

2019-03-06 17:44 UTC, BubuntuClu commented on rack/middleware/time_format.rb
> +    @app.call(env)
вызов не надо переносить сюда. он должен остаться в класс основного приложения. ты просто должен из него вызвать метод класса TimeFormat, который сделает для тебя форматирование.

2019-03-07 05:49 UTC, BubuntuClu commented on rack/middleware/time_format.rb
> +    @invalid_formats = []
код этого метода можно поместить в `call`, если это "сервис"

2019-03-07 05:49 UTC, BubuntuClu commented on rack/app.rb
> +  def call(env)
Удобно использовать объект класса `Rack::Response` для формирования ответа.

```
class App
  def call(env)
   request = Rack::Request.new(env)
    #проверка на путь, куда идет запрос
     
    format = TimeFormat.new(@request.params).call
    #смотришь результат и отвечаешь должным образом
  end
end
```

2019-03-07 17:20 UTC, BubuntuClu commented on rack/middleware/time_format.rb
> +    params = Rack::Request.new(env).params
только это все в `app.rb`, и в `app.rb`, ты обращаешься к `TimeFormat` для формирования ответа.
должно быть так `app.rb` с `response`, а TimeFormat` подготавливает текст для `response`

2019-03-07 19:47 UTC, psylone requested changes

2019-03-07 19:47 UTC, psylone commented on rack/config.ru
> +use TimeFormat
На самом деле, это не middleware. К middleware относятся вещи которые влияют на ход выполнения запроса в целом. Например, установка заголовков кэширования или вычисление времени выполнения запроса.

У нас же `TimeFormat` это конкретный класс который реализует бизнес логику приложения. Поэтому стоит вызывать его явно внутри класса `App`.

2019-03-07 19:47 UTC, psylone commented on rack/middleware/time_format.rb
> +  OK_STATUS = 200
Этот класс ничего не должен знать о rack приложении и в частности о HTTP протоколе.

2019-03-08 17:22 UTC, psylone approved these changes

2019-03-08 17:22 UTC, psylone commented on rack/app.rb
> +require_relative 'helper/time_format'
Можно на тот же уровень положить, по факту это самостоятельный класс, реализующий бизнес логику.

2019-03-08 17:22 UTC, psylone commented on rack/app.rb
> +    if params.has_key?('format')
На самом деле, нам нужно проверять PATH запроса. Это можно сделать выше в методе `call`, а здесь уже проверять наличие параметра.

2019-03-08 19:13 UTC, merged